'use strict';
(function(root){
  let worker=null,seq=0,pending=new Map(),status='idle',provider='none',progress=0,lastError=null,lastMs=0,primed=false;
  function heuristicLanguage(text){const s=String(text||'').trim();if(/[\u3040-\u30ff\u3400-\u9fff]/.test(s))return'ja';if(/[ãõáéíóúâêôç]/i.test(s)||/\b(o|a|os|as|de|da|do|para|por|com|não|uma|um|porta|empurre|puxe|saída|entrada|atenção)\b/i.test(s))return'pt';return'en'}
  async function detectLanguage(text,requested='auto'){if(requested&&requested!=='auto')return requested;try{if(root.LanguageDetector?.availability&&root.LanguageDetector?.create){const avail=await root.LanguageDetector.availability({expectedInputLanguages:['pt','en','ja']});if(avail!=='unavailable'){const d=await root.LanguageDetector.create({expectedInputLanguages:['pt','en','ja']});const r=await d.detect(String(text||''));d.destroy?.();if(r?.[0]?.detectedLanguage)return String(r[0].detectedLanguage).split('-')[0]}}}catch(_){}return heuristicLanguage(text)}
  async function builtInTranslate(text,source,signal,onProgress){
    if(!root.Translator?.availability||!root.Translator?.create)return null;const opts={sourceLanguage:source,targetLanguage:'ja'};let avail;try{avail=await root.Translator.availability(opts)}catch(_){return null}if(avail==='unavailable')return null;onProgress?.({stage:'browser-translator',availability:avail,progress:avail==='available'?1:0});
    try{const tr=await root.Translator.create({...opts,monitor:m=>m.addEventListener('downloadprogress',e=>onProgress?.({stage:'browser-translator',progress:Number(e.loaded)||0}))});const out=await tr.translate(text,{signal});tr.destroy?.();return String(out||'').trim()||null}catch(e){if(signal?.aborted)throw e;return null}
  }
  function ensureWorker(){if(worker)return worker;if(typeof Worker==='undefined')throw new Error('Web Worker indisponível');worker=new Worker('js/language-ai-worker-v1.js',{type:'module'});worker.onmessage=e=>{const m=e.data||{};if(m.type==='status'){status=m.status||status;provider=m.provider||provider;progress=Number(m.progress)||0;for(const p of pending.values())p.onProgress?.(m);return}const p=pending.get(m.id);if(!p)return;pending.delete(m.id);if(m.type==='result'){status='ready';provider=m.provider||'transformers';lastMs=Number(m.ms)||0;p.resolve(m)}else{status='error';lastError=m.error;p.reject(new Error(m.error||'Falha na tradução local'))}};worker.onerror=e=>{status='error';lastError=e.message||'Falha no worker de idioma';for(const p of pending.values())p.reject(new Error(lastError));pending.clear();worker?.terminate();worker=null};return worker}
  function workerTranslate(texts,source,{signal,onProgress,timeoutMs=600000}={}){const w=ensureWorker(),id=++seq;status='loading';return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(new Error('Tradução local excedeu o tempo limite'));dispose()},timeoutMs);const entry={onProgress,resolve:v=>{clearTimeout(timer);resolve(v)},reject:e=>{clearTimeout(timer);reject(e)}};pending.set(id,entry);const abort=()=>{if(!pending.has(id))return;pending.delete(id);clearTimeout(timer);reject(new DOMException('Aborted','AbortError'));dispose()};signal?.addEventListener('abort',abort,{once:true});w.postMessage({type:'translate',id,texts,source})})}
  async function translateBatch(texts,{sourceLanguage='auto',signal,onProgress}={}){
    const clean=(texts||[]).map(x=>String(x||'').trim()).filter(Boolean);if(!clean.length)return[];const started=performance?.now?.()??Date.now();const source=await detectLanguage(clean.join(' '),sourceLanguage);if(source==='ja')return clean.map(text=>({source:text,sourceLanguage:'ja',japanese:text,provider:'identity'}));
    const built=[];let builtOk=true;for(let i=0;i<clean.length;i++){const t=await builtInTranslate(clean[i],source,signal,onProgress);if(!t){builtOk=false;break}built.push({source:clean[i],sourceLanguage:source,japanese:t,provider:'browser-translator'})}
    if(builtOk&&built.length===clean.length){primed=true;status='ready';provider='browser-translator';lastMs=(performance?.now?.()??Date.now())-started;return built}
    const r=await workerTranslate(clean,source,{signal,onProgress});primed=true;return(r.results||[]).map((j,i)=>({source:clean[i],sourceLanguage:source,japanese:String(j||''),provider:r.provider||'transformers'}))
  }
  function dispose(){for(const p of pending.values())p.reject(new Error('Tradução reiniciada'));pending.clear();if(worker){try{worker.postMessage({type:'dispose'})}catch(_){}worker.terminate();worker=null}status='idle';progress=0;provider='none'}
  function snapshot(){return{status,provider,progress,lastMs,primed,error:lastError}}
  const api={heuristicLanguage,detectLanguage,translateBatch,dispose,snapshot};root.MiraLanguageAIV1=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
