'use strict';
const fs=require('fs'),assert=require('assert');
const app=fs.readFileSync('js/app.js','utf8'),html=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8'),hier=fs.readFileSync('js/visual-hierarchy-v1.js','utf8'),world=fs.readFileSync('js/world-model-v2.js','utf8');
assert(html.includes('Pre-Alpha 2.1 · Perception Consolidation'));
assert(html.includes('visionRuntimeProfile'));
assert(sw.includes('mira-nihongo-v1-prealpha2-1-r1'));assert(sw.includes('./js/world-model-v2.js'));
assert(app.includes("localStorage.getItem('mn-v05-autofreeze')!=='0'"),'new install Auto Freeze must default ON');
assert(app.includes("localStorage.setItem('mn-v05-autofreeze',state.autoFreezeEnabled?'1':'0')"),'explicit Auto Freeze choice must persist');
assert(app.includes('requestVideoFrameCallback'),'video frame scheduler must be used when available');
assert(app.includes('startPerformanceObservers')&&app.includes('stopPerformanceObservers'),'performance observatory missing');
assert(!app.includes('visionScheduler'),'legacy second scheduler must be removed from runtime');
assert(app.includes("perceptionRouter.run('live-analysis'"));assert(app.includes("perceptionRouter.run('scene-analysis'"));assert(app.includes("perceptionRouter.run('point-analysis'"));assert(app.includes("perceptionRouter.run('human-arbitration'"));assert(app.includes("perceptionRouter.run('ocr'"));
const point=app.indexOf('async function analyzeFrozenPoint'),pointEnd=app.indexOf('function setPerceptionMode',point);assert(point>0&&pointEnd>point);const pointSrc=app.slice(point,pointEnd);assert(pointSrc.indexOf('analyzeHands')<pointSrc.indexOf('ensureVerifier'),'human specialist must precede generic verifier in drill-down');
const specialistStart=app.indexOf('async function analyzeSpecialists'),specialistEnd=app.indexOf('function expandBox',specialistStart);const specialistSrc=app.slice(specialistStart,specialistEnd);assert(!specialistSrc.includes('.segment('),'automatic scene specialists must not run segmentation');
assert(app.includes("if(!top||!top.structural"),'large-region multi-scale may only promote structural classes');
assert(app.includes("current==='person'"));assert(app.includes("current==='hand'"));assert(app.includes('specialistTargetCanvasBox'));
assert(app.includes('temporalTracker?.reset?.()'),'temporal tracker must reset between observations');
assert(hier.includes("bottle:['bottle_cap','label']"));assert(hier.includes("finger:['fingernail']"));assert(!hier.includes("finger:['nail']"));assert(hier.includes("cabinet:['drawer','door','handle','shelf']"));
assert(world.includes("trackingId:input.trackingId||null"));assert(world.includes('text:cleanText(input.text)'));assert(world.includes("'PART_OF'"));
console.log('prealpha2.1 permanent regression guards: OK');
